# Generated by Django 5.1.3 on 2024-11-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Select Day', max_length=20)),
                ('week', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Select', max_length=5)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choir_practice', to='accounts.choirmemberaccount')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_choir_attendance', to='accounts.churchaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(max_length=200)),
                ('number_of_men', models.IntegerField(blank=True, null=True)),
                ('number_of_women', models.IntegerField(blank=True, null=True)),
                ('number_of_male_children', models.IntegerField(blank=True, null=True)),
                ('number_of_female_children', models.IntegerField(blank=True, null=True)),
                ('total_attendees', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Select', max_length=20)),
                ('year', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_attendance', to='accounts.churchaccount')),
            ],
        ),
    ]
