# Generated by Django 5.1.3 on 2024-11-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('church_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choirattendance',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.AddField(
            model_name='choirattendance',
            name='activities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='church_activity.churchactivity'),
            preserve_default=False,
        ),
    ]
