# Generated by Django 5.1.3 on 2024-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_choirattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchserviceattendance',
            name='vistor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
