# Generated by Django 5.1.3 on 2024-12-01 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_churchserviceattendance_vistor'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchserviceattendance',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
