# Generated by Django 5.1.3 on 2024-12-01 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_churchserviceattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirattendance',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
